name: backend

type: nodejs:18

build:
  flavor: none

variables:
    env: 
        MEDUSA_DISABLE_TELEMETRY: 1
        NODE_ENV: production

hooks:
  build: |
    corepack yarn global add @medusajs/medusa-cli
    corepack yarn install --immutable
    corepack yarn run build
  deploy: |
    corepack yarn run medusa telemetry --disable
    corepack yarn run medusa migrations run

# The configuration of app when it is exposed to the web.
web:
  commands:
    start: |
      corepack yarn run medusa start -p=$PORT

# The size of the persistent disk of the application (in MB).
disk: 1024

relationships:
  pg: "postgres:postgresql"
  redis: "redis:redis"

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  "/.cache":
    source: local
    source_path: yarn-cache
  "/.config":
    source: local
    source_path: yarn-config
  "uploads":
    source: local
    source_path: uploads
