# The name of this app. Must be unique within a project.
name: storefront

type: nodejs:18

build:
  flavor: none

size: L

resources:
  base_memory: 1024
  memory_ratio: 1024

hooks:
  build: |
    set -e
    corepack yarn install --immutable --production=false
#  post_deploy: |
#    set -e
#    cd $PLATFORM_APP_DIR
#    corepack yarn build

web:
  commands:
    start: |
      corepack yarn run dev -p $PORT


disk: 2048

mounts:
  /.cache:
    source: local
    source_path: 'cache'
  /.next:
    source: local
    source_path: 'next'