# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/store":
  type: upstream
  upstream: "backend:http"

"https://{default}/store":
  type: redirect
  to: "https://www.{default}/store"

"https://admin.{default}/":
  type: upstream
  upstream: "admin:http"