# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://api.{default}/store":
  type: upstream
  upstream: "backend:http"

"https://www.{default}":
  type: upstream
  upstream: "storefront:http"

"https://{default}":
  type: redirect
  to: "https://www.{default}"